use_frameworks!

target 'CardParts_Example' do
  pod 'CardParts', :path => '../'

  target 'CardParts_Tests' do
    inherit! :search_paths
    pod 'CardParts', :path => '../'
  end
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

